spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatops
  data:
    redis:
      host: localhost
  rabbitmq:
    host: localhost
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  minio:
    endpoint: localhost

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
