pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install') {
            steps {
                sh 'cd api && pnpm install'
                sh 'cd client && pnpm install'
            }
        }

        stage('Build') {
            steps {
                sh 'cd api && pnpm run build'
                sh 'cd client && pnpm run build'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker compose up -d --build'
                sh 'docker compose exec api npx prisma migrate deploy'
            }
        }
    }
}
